### ISSUE TITLE
Matrix expansion fails in Write-NuGetPackage

### ISSUE THREAD

**Issue by virmitio** [coapp/coapp.powershell#6]
v 1.23.196

The following code snippet will throw an exception (assuming the required `nuspec` section is provided):

``` c#
nuget {
files { 
("Win32,x64", "v100,v110") => {
};
};
};
```

The exception and stacktrace are included below.  The line and character number below reflect the code snippet above.

```
(3,8):Error TokenNotExpected:Invalid token in selector declaration--found ', '

   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseSelector(IEnumerable`1 terminators, SourceLocation sourceLocation, String selectorName, String parameter)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseSelector(IEnumerable`1 terminators, SourceLocation sourceLocation, String selectorName, String parameter)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.ParseItemsInDictionary(ObjectNode context, Continuation onComplete, Boolean justOneItem, String prefix)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.Global(Continuation onComplete)
   at ClrPlus.Scripting.Languages.PropertySheetV3.PropertySheetParser.Global(Continuation onComplete)
   at ClrPlus.Scripting.Languages.PropertySheetV3.RootPropertySheet.ParseText(String propertySheetText, String originalFilename)
   at ClrPlus.Scripting.MsBuild.Packaging.PackageScript..ctor(String filename)
   at CoApp.Powershell.Commands.WriteNuGetPackage.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by virmitio** [comment]
Not A Bug.
This was actually a manifestation of #8
