### ISSUE TITLE
Package update problem

### ISSUE THREAD

**Issue by kreuzerkrieg** [coapp/coapp.powershell#78]
I'm constantly getting the following message when updating packages:
WARNING: Could not install package 'NativePackageName.redist 2.7.352'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
when restores everything works OK, but when I want to update the above happens, leaving original packages in non working state (target file crippled)
It doesn't happen when I update from within VS, only when running in command line using Nuget.exe (tried various versions of nugget).
Cannot figure it out, is it package problem? CoApp? Nuget?
Ideas?

**Comment by kreuzerkrieg** [comment]
When setting the verbosity to "detail" I see following callstack
WARNING: System.InvalidOperationException: Could not install package NativePackageName.redist 2.7.530'. You are trying to install this package into a proj
ect that targets '.NETFramework,Version=v4.0', but the package does not contain
any assembly references or content files that are compatible with that framework
. For more information, contact the package author.
   at NuGet.ProjectManager.ExtractPackageFilesToProject(IPackage package)
   at NuGet.ProjectManager.AddPackageReferenceToProject(IPackage package)
   at NuGet.ProjectManager.Execute(PackageOperation operation)
   at NuGet.ProjectManager.Execute(IPackage package, IPackageOperationResolver r
esolver)
   at NuGet.ProjectManager.AddPackageReference(IPackage package, Boolean ignoreD
ependencies, Boolean allowPrereleaseVersions)
   at NuGet.ProjectManager.UpdatePackageReference(String packageId, Func`1 resol
vePackage, Boolean updateDependencies, Boolean allowPrereleaseVersions, Boolean
targetVersionSetExplicitly)
   at NuGet.ProjectManager.UpdatePackageReference(String packageId, SemanticVers
ion version, Boolean updateDependencies, Boolean allowPrereleaseVersions)
   at NuGet.Commands.UpdateCommand.UpdatePackages(IPackageRepository localReposi
tory, IFileSystem sharedRepositoryFileSystem, ISharedPackageRepository sharedPac
kageRepository, IPackageRepository sourceRepository, IPackageConstraintProvider
constraintProvider, IPackagePathResolver pathResolver, IProjectSystem project)

**Comment by kinghajj** [comment]
For what it's worth, I'm running into a similar issue at work right now. The native library I packaged is set to .NET 4.0 compatibility, and the project I'm trying to use that package in is also set to .NET 4.0.

**Comment by zarkara** [comment]
FWIW I found that commandline update does not work with native projects. If anyone knows of a way to simulate/automate the VS IDE upgrade nuget packages action that would be awesome.
